### ISSUE TITLE
Requesting Video

### ISSUE THREAD

**Issue by AYMENJD** [melchor629/youtubedl-audio-api#2]
Hello i love your project and i want you to add video version the reason is i want it for my Telegram bot that download video/audio from YouTube and can be deployed in heroku thank you

If you want to contact me in Telegram my user : https://t.me/K6KKK .
+ Telegram is home to developer you can make bot managing your projects and server and control everything by mobile .

Best regards, 😘

**Comment by melchor629** [comment]
Hi. I think it is possible to implement the video as well for the API :) It will change a bit the API, but everything will be documented properly like now.

I will start with this this week and I will be back to this issue with the status.

Thanks for raising the issue

**Comment by AYMENJD** [comment]
Thank you + i love your project because when i Request audio it will extract one or two urls and save it thats make less request to YouTube and we will miss yt error : HTTP 429 :Too many request 😂😂

god bless you 😇

**Comment by melchor629** [comment]
I'm glad you like my project :)

The cache thing is what makes it very powerful I think, to avoid the `Too many requests` errors as you mentioned.

I think I have a base for the new feature. I will push the changes to the repository so you can give it a try now ;)

**Comment by AYMENJD** [comment]
Sure 😘

**Comment by AYMENJD** [comment]
Perfect work keep going 👍

Some suggestion :
Make the json more pretty and gives video info like VideoAuthor, Duration, lengthSeconds, likes, viewCount .

Download the video in heroku server and return the video url that stored on heroku server . I knew that's heroku has limits but the video can deleted from heroku server after one or two days from download and make it very perfect 👌 

if you want contact me on Tg : https://t.me/K6KKK

Best regards,

**Comment by melchor629** [comment]
Hi. The JSON formatting is managed by Flask, and it is correct to be like that (this is intended to be used by machines). In a development environment, the JSON is pretty formatted. In Firefox, you can see the JSON pretty, or you can use any external formatter to see the JSONs. Anyway, the README has example responses with pretty format.

I did not tried this, but this [StackOverflow answer](https://stackoverflow.com/questions/16908943/display-json-returned-from-flask-in-a-neat-way) suggests to set up `JSONIFY_PRETTYPRINT_REGULAR` environment variable to `True` (Config Var in Heroku) and it will print them pretty. Futhermore, I will check if I can change this from code with some option so you can get this.

About download the video, this is out of scope of this project. The scope of the API is to get some information about qualities availables and URLs, so other projects can do whatever they want with that information. Also Heroku has some big limitations on space (as you know), you will reach quickly that limits with 1080p videos (or higher). _I think limit was 500MB of space._ If you need to download the video, you can do it on your bot (but take care of the space limits). The best way to avoid this limits is to use an external storage (a S3-like storage, Backblaze B2...). Hope you understand this.

Last point, with the Youtube API you can get information about the video, but I think is useful to include them in this API. I will see what I can do with that, all depends on youtube-dl project.

Thanks.

**Comment by AYMENJD** [comment]
I see Thank You 😊

**Comment by melchor629** [comment]
Well, then. I be able to add some extra information about the video in the response (as you requested). Also, added the option to return the JSONs pretty (with the variable mentioned before `JSONIFY_PRETTYPRINT_REGULAR`).

Check out now the new code and see if it is ok with these new features :)

**Comment by AYMENJD** [comment]
You are SuperDev now is very pretty and from one request i got what i want thank u very much i think you forget to add two value in urls(key).
The first value is audio and The second value video(360p with audio) and that's it your project now is very super and good thank you again i hope that i can help you but im a beginner PHP dev 🌚❤️

Note: join in telegram and try make bot project may you be famous 😂 .

Best regards,

**Comment by melchor629** [comment]
If you request the URLs with default values (no quality IDs specified) the result is a bit unpredictable. I can look for this and handle it differently. But I cannot ensure anything.

Nevertheless, I recommend you to properly pick the audio and video qualities by asking the API first which ones are available (`/api/<video-id>/formats`) and the send the request with those qualities pre-selected (`/api/<video-id>/<video-quality-id>,<audio-quality-id>`). I should better explain this thing in the README hehe

About the URLs, the key represents the quality ID and the value the URL for this. That's why I mentioned before to pre-select the qualities, so you will get what you expect to get ;)

When this feature is complete, I will check out your bot :)

I'll see what I can do from here. Thanks for everything :D

**Comment by AYMENJD** [comment]
😘

**Comment by melchor629** [comment]
Hi, did some changes on the API for the default quality audio/video (no more weird 360p video URL).

So. If you think all this changes fulfils this new feature, feel free to close the issue. If there is still something wrong, comment it here.

Thanks for your time and patience, I think this feature is awesome (and never thought about adding it).

**Comment by AYMENJD** [comment]
TnQ everything is good just add deploy to Heroku button on Readme.md file and i hope you get Your wish God bless you 😇 

AYMEN From Saudi Arabia ❤️😘

Best regards,
