### ISSUE TITLE
YouTube IP Address and time limits

### ISSUE THREAD

**Issue by mobile-appz** [melchor629/youtubedl-audio-api#3]
Hi just wondering if the audio URL that is generated from the API is only accessible by the original IP address that made the network request in Youtube DL? Thanks

**Comment by melchor629** [comment]
Hello. The first question is a bit difficult to answer:

- If you access using the same IP address that generated the request through YoutubeDL, it will always work (obviously).
- If the video has no country restrictions, it should work from everywhere without trouble.
- If the video has country restrictions, it may work, it may not work. Even it may not work from inside the same country (but this is less likely as I experienced).

For the time limits, I don't exactly know the time the URL is valid. From my experience it is usually around 15-20 minutes. The cache used in the API stores the result for 10 minutes.

Hope this answers your questions :)

**Comment by mobile-appz** [comment]
@melchor629 Thanks very much for your help, much appreciated.

**Comment by melchor629** [comment]
Cool, glad I could help you with this :)

If there is no inconvenience, I will close the issue. Thanks for asking.
